server:
  port: 8081
zuul.ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
zuul:
  sensitiveHeaders:
  routes:

    oauth-as:
      path: /auth/**
      url: http://localhost:8082
      sensitiveHeaders: Cookie,Set-Cookie

    oauth-rs:
      path: /rs/**
      url: http://localhost:8084

