server:
  port: 8081
#  ssl:

zuul.ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
zuul:
  sensitiveHeaders:
  routes:

    oauth-as:
      path: /auth/**
      url: http://localhost:8082
      sensitiveHeaders: Cookie,Set-Cookie

    oauth-rs:
      path: /rs/**
      url: http://localhost:8084

    oauth-scheduling:
      path: /scheduling/**
      url: http://localhost:8085

    oauth-setting-management-api:
      path: /settings/**
      url: http://localhost:8086


